language: node_js
node_js:
  - "stable"
  - "unstable"
  - "4.2"
before_install: npm install -g grunt-cli
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "unstable"
services:
  - mongodb
